-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
--
-- vim.api.nvim_create_autocmd("Filetype", {
--   pattern = "norg",
--   callback = function()
--     vim.keymap.set("n", "<leader>od", "<Plug>(neorg.qol.todo-items.todo.task-cycle)", { buffer = true })
--   end,
-- })
